AllCops:
  Exclude:
    - 'spec/**/*'
    - 'gems/**/*'
    - 'utils/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/*'
Lint/HandleExceptions:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
